-d D:\DOC\hardware_project\led_hard\impl\gwsynthesis\led_hard.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\DOC\hardware_project\led_hard\src\top_sct.cst
-cfg D:\DOC\hardware_project\led_hard\impl\pnr\device.cfg
-sdc D:\DOC\hardware_project\led_hard\src\top_sdc.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
