-d D:\DOC\hardware_project\hard_ware_led\impl\gwsynthesis\hard_ware_led.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\DOC\hardware_project\hard_ware_led\src\hard_ware_led.cst
-cfg D:\DOC\hardware_project\hard_ware_led\impl\pnr\device.cfg
-sdc D:\DOC\hardware_project\hard_ware_led\src\hard_ware_led.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
