-d D:\DOC\hardware_project\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\DOC\hardware_project\fpga_project\src\fpga_project.cst
-cfg D:\DOC\hardware_project\fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
