-d D:\DOC\nianmobai\Hit-Gophers-base-on-tangnano4k\hardware_project\game\impl\gwsynthesis\game.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\DOC\nianmobai\Hit-Gophers-base-on-tangnano4k\hardware_project\game\src\game.cst
-cfg D:\DOC\nianmobai\Hit-Gophers-base-on-tangnano4k\hardware_project\game\impl\pnr\device.cfg
-sdc D:\DOC\nianmobai\Hit-Gophers-base-on-tangnano4k\hardware_project\game\src\game.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
